import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "./componenets/sideMenu/sideMenu";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"flex flex-row border border-red-500 "}>
        <SideMenu />
        <div className="border border-yellow-500 w-full">
        {children}

        </div>
      </body>
    </html>
  );
}
